### ISSUE TITLE
unmet libR.dylib dependency in conda environment

### ISSUE THREAD

**Issue by CampanaOxidada** [greenelab/hgsc_subtypes#32]
there is a linking error originating from libR:
(hgsc_subtypes) $ Rscript INSTALL.R 
dyld: Library not loaded: @rpath/libicuuc.54.dylib
  Referenced from: /Users/rbell/anaconda/envs/hgsc_subtypes/lib/R/lib/libR.dylib
  Reason: image not found
Abort trap: 6

on Mac (Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64)

using this environment

name: hgsc_subtypes 
channels:
- r
- bioconda
dependencies:
- r-checkpoint=0.4.0
- r-wgcna=1.51
- bioconductor-curatedovariandata=1.14.0
- bioconductor-affy=1.50.0
- bioconductor-biobase=2.34.0
- bioconductor-biomart=2.28.0
- bioconductor-sva=3.20.0
- bioconductor-impute=1.46.0
- bioconductor-siggenes=1.44.0
- bioconductor-limma=3.28.2
- bioconductor-annotationdbi=1.38.0
- bioconductor-go.db=3.4.0
- bioconductor-preprocesscore=1.34.0
- bioconductor-biocparallel=1.6.6
- bioconductor-geoquery=2.38.4
- bioconductor-doppelgangr=1.4.1
- bioconductor-gsva=1.24.1

**Comment by gwaygenomics** [comment]
Thanks for posting @CampanaOxidada

I cannot reproduce the error on my Mac. Although it looks to be a somewhat common problem. A potential solution is discussed in conda/conda#3113.

We may need to add `r-essentials` to the conda environment Can you post any updates as you work through this issue? 

I'm more convinced now that we should be moving all dependencies in INSTALL.R to the environment file! (via #11)

**Comment by CampanaOxidada** [comment]
My conda hgsc_sybtypes environment had a bunch of extra conda-forge packages installed inadvertantly.  Removing and replacing the env solved the problem
