### ISSUE TITLE
darwin11 vs. darwin14 

### ISSUE THREAD

**Issue by CampanaOxidada** [greenelab/hgsc_subtypes#38]
Calls to library() in R code from aaces_subtypes_pipeline.sh are resulting in 
Error: package ‘sva’ was built for x86_64-apple-darwin14.5.0
Error: package ‘Biobase’ was built for x86_64-apple-darwin14.5.0
Error: package ‘affy’ was built for x86_64-apple-darwin14.5.0
Error: package ‘limma’ was built for x86_64-apple-darwin14.5.0
etc
R invoked in hgsc_subtypes env has the platform as x86_64-apple-darwin11.4.2
> Sys.getenv('R_PLATFORM')
[1] "x86_64-apple-darwin11.4.2"

**Comment by gwaygenomics** [comment]
Code was only tested with Ubuntu 16.04 this morning, I will try to update conda environment to be more mac friendly

**Comment by gwaygenomics** [comment]
I was able to reproduce this error, and possibly fixed it in #39

@CampanaOxidada can you take a look?
