### ISSUE TITLE
getSamNames error

### ISSUE THREAD

**Issue by CampanaOxidada** [greenelab/hgsc_subtypes#41]
The attached file is the output from a run of the AACES-data fork. On line 1646 of hgsc_analysis.out there is an error coming from the getSamNames() function called in RunSam(). It looks to me like it happened in one of the sam runs for TCGA. The scripts completed but I’m not sure the entire complement of output files were created (cf before and after)
[hgsc_analysis.out.gz](https://github.com/greenelab/hgsc_subtypes/files/1416727/hgsc_analysis.out.gz)
[ls-lR_before.txt](https://github.com/greenelab/hgsc_subtypes/files/1416728/ls-lR_before.txt)
[ls-lR_after.txt](https://github.com/greenelab/hgsc_subtypes/files/1416729/ls-lR_after.txt)

**Comment by gwaygenomics** [comment]
> It looks to me like it happened in one of the sam runs for TCGA.

Yeah, looks like it. Here are lines `1638 to 1649` in `hgsc_analysis.out`:

```
Running SAM on: TCGA_eset 
      For k = 2 , Control: Cluster 1 
      For k = 2 , Control: Cluster 2 
      For k = 2 , Control: Cluster 1 
      For k = 2 , Control: Cluster 2 
      For k = 3 , Control: Cluster 1 
      For k = 3 , Control: Cluster 2 
      For k = 3 , Control: Cluster 3 
Error in `colnames<-`(`*tmp*`, value = c("SAMD_1", "SAMP_1", "SAMD_2",  : 
  'names' attribute [8] must be the same length as the vector [6]
Calls: RunSam -> colnames<- -> colnames<-
Execution halted
```

It is strange that in that `hgsc_analysis.out` file that `A.run_kmeans_SAM.R` works two times before (since it is run multiple times with different command arguments). What are the command arguments used when it throws the error?

**Comment by gwaygenomics** [comment]
one quick sanity check could be to compare your local copy of `TCGA_eset_samplesRemoved.csv` to [the github version](https://github.com/greenelab/hgsc_subtypes/blob/master/1.DataInclusion/Data/GoodSamples/TCGA_eset_samplesRemoved.csv).

this error smells like it could be a sample issue

**Comment by CampanaOxidada** [comment]
They are the same.

**Comment by CampanaOxidada** [comment]
The error looked familiar so I searched my notes.  It looks like I've seen this particular error before back when I was dissecting the code.  I tried nullifying attrs: attr(krange_grid, "out.attrs") <- NULL but the notes don't say whether it worked or not.

**Comment by gwaygenomics** [comment]
I believe it is a sample issue. Either way, whether this solves the issue or not, I found a sample issue. I outline the issue below.

I remembered that TCGA had 2 low correlating samples that doppelgangR should have removed. Levi knew about this issue and discusses it in section 3 of the [curatedOvarianData vignette](https://www.bioconductor.org/packages/devel/data/experiment/vignettes/curatedOvarianData/inst/doc/curatedOvarianData_vignette.pdf). The two samples are `"TCGA_eset:TCGA.24.1927` and `"TCGA_eset:TCGA.31.1955"`. I found this by running:

```
source(system.file("extdata","patientselection.config",package="curatedOvarianData"))
paste(tcga.lowcor.outliers)
```

The original publication correctly filtered these 2 samples out. Note that in [Table S3](http://www.g3journal.org/content/early/2016/10/10/g3.116.033514.supplemental) there are 499 TCGA samples and do not include the two samples above. Moreover, in the [zenodo full build archive](https://zenodo.org/record/53990#.WfI1cXWPLAI), we see in the `hgsc_analysis.out` file on line 502:

```
Remove 2 low-correlating samples from TCGA_eset 
```

We don't see that in the `hgsc_analysis.out` file provided above. **We also see that these two samples are retained in the [good samples file](https://github.com/greenelab/hgsc_subtypes/blob/master/1.DataInclusion/Data/GoodSamples/TCGA_eset_samplesRemoved.csv)**. These should not be here. It is unclear when they were added, probably when the `doppelgangR` scripts were updated ([commit history](https://github.com/greenelab/hgsc_subtypes/commits/5a9b61ee008b7f7204fec956806fadf9962503c6/1.DataInclusion/Scripts/A.getInclusion.R)), but they should be removed. If I remember correctly, they caused headache when they were included.

Its also possible that the move away from an internal doppelgangR function (which we used when doppelgangR was not a standalone library) performs the removal, but the standalone package (i.e. [`doppelgangR::doppelgangR` on line 167](https://github.com/greenelab/hgsc_subtypes/blob/master/1.DataInclusion/Scripts/A.getInclusion.R#L166) does not make the removal.

**Comment by gwaygenomics** [comment]
lets see if I can file a PR to make this fix quickly. Then you can try rerunning the analysis and check if it fixes the original issue

**Comment by gwaygenomics** [comment]
@CampanaOxidada - I cannot reproduce the error.

I ran each call to `A.run_kmeans_SAM.R` in the [aaces pipeline](https://github.com/greenelab/hgsc_subtypes/blob/master/aaces_subtypes_pipeline.sh) individually and I do not run into any issues. Are any files on your local machine different than the github versions? 

I am currently checking one more thing. I ran each call individually, separate from the entire pipeline. I am going to get NMF cluster membership (by running `D.NMF.R`) and then rerun `A.run_kmeans_SAM.R` using the updated NMF subtype assignments. This is my next best guess that's going wrong. Maybe the 2 low correlating samples were included in the NMF subtype labels?

One important thing to note about this is that I am running these scripts without aaces data.

**Comment by gwaygenomics** [comment]
Running NMF before `A.run_kmeans_SAM.R` did not induce the error. 

I am not sure if including the aaces data here would result in an error in TCGA clustering (since I am using the genes defined when aaces is included). Are you still getting this error @CampanaOxidada ?

**Comment by CampanaOxidada** [comment]
@gwaygenomics, the last time I ran with AACES the error did _not_ occur.  Its baffling.

**Comment by gwaygenomics** [comment]
hmm, strange. Lets consider this a vulnerability then, but one that should not stop progress. I will close this issue for now, but feel free to reopen if there are any updates.
